version: '3.9'

services:
  database:
    image: mongo:5.0.7
    container_name: database
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
  backend:
    image: node:latest
    container_name: backend
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm run dev
    depends_on:
      database:
          condition: service_healthy
    environment:
      MONGO_URI: mongodb://root:root@database
    build:
      context: ./backend
      dockerfile: Dockerfile
  frontend:
    image: node:latest
    container_name: frontend
    restart: always
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev
    environment:
      - BASE_URL=http://localhost:3000
      - VUE_APP_API_URL=http://localhost:3001
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile